### ISSUE TITLE
Invalid call. Nonexistent function 'calculate_flow_field' in base 'Node'. Problem

### ISSUE THREAD

**Issue by zhexie314** [arnemileswinter/godot-tilemap-flowfields#1]
when i run the Example scene,i got this bug: Invalid call. Nonexistent function 'calculate_flow_field' in base 'Node'. 

godot V3.5

mac mini M1 macos monterey

**Comment by arnemileswinter** [comment]
it's not compiled for Mac, I'm too poor

**Comment by DSPerson** [comment]
how to compiled on mac?

**Comment by arnemileswinter** [comment]
> how to compiled on mac?

I don't know and I don't have access to any Mac computer. If you manage to compile it I'll gratefully merge a PR!
